# Generated by Django 3.2.6 on 2021-09-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='partnership1', to='main.person')),
                ('partner1_parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child_rel1', to='main.partnership')),
                ('partner2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='partnership2', to='main.person')),
                ('partner2_parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child_rel2', to='main.partnership')),
            ],
        ),
    ]
