# Generated by Django 3.2.6 on 2021-09-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210928_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='partner1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='partnership1', to='main.person'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partner1_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child_rel1', to='main.partnership'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partner2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='partnership2', to='main.person'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partner2_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child_rel2', to='main.partnership'),
        ),
    ]
