# Generated by Django 3.2.6 on 2021-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partnership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
