# Generated by Django 3.2.6 on 2021-10-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
